INSERT INTO TEAM
(NAME)
VALUES ('Paris SG');

INSERT INTO TEAM
(NAME)
VALUES ('Marseille');

INSERT INTO TEAM
(NAME)
VALUES ('Lyon');

INSERT INTO TEAM
(NAME)
VALUES ('Bordeaux');

INSERT INTO TEAM
(NAME)
VALUES ('Toulouse');

INSERT INTO TEAM
(NAME)
VALUES ('Valenciennes');

INSERT INTO TEAM
(NAME)
VALUES ('St-Etienne');

INSERT INTO PLAYER
( FIRSTNAME, LASTNAME, EQUIPE_ID )
VALUES ( 'Zlatan', 'Ibrahimovic', 1);

INSERT INTO PLAYER
( FIRSTNAME, LASTNAME, EQUIPE_ID )
VALUES ( 'Nicolas', 'NKoulou', 2);

INSERT INTO PLAYER
( FIRSTNAME, LASTNAME, EQUIPE_ID )
VALUES ( 'Steed', 'Malbranque', 3);

INSERT INTO PLAYER
( FIRSTNAME, LASTNAME, EQUIPE_ID )
VALUES ( 'Jaroslav', 'Plasil', 4);

INSERT INTO PLAYER
( FIRSTNAME, LASTNAME, EQUIPE_ID )
VALUES ( 'Wissam', 'Ben Yedder', 5);

INSERT INTO PLAYER
( FIRSTNAME, LASTNAME, EQUIPE_ID )
VALUES ( 'Gael', 'Danic', 6);

INSERT INTO PLAYER
( FIRSTNAME, LASTNAME, EQUIPE_ID )
VALUES ( 'Loic', 'Perrin', 7);

